# Generated by Django 6.0.1 on 2026-01-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='id',
        ),
        migrations.AlterField(
            model_name='dept',
            name='DEPT_NO',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dept',
            name='Dname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='LOC',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='EMPNO',
            field=models.IntegerField(unique=True),
        ),
    ]
