# Generated by Django 6.0.1 on 2026-01-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_emp_comm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='DEPT_NO',
            new_name='DEPTNO',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='Dname',
            new_name='DNAME',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='Comm',
            new_name='COMM',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='DEPT_NO',
            new_name='DEPTNO',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='Ename',
            new_name='ENAME',
        ),
    ]
