# Generated by Django 6.0.1 on 2026-01-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_dept_no_dept_deptno_rename_dname_dept_dname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='MGR',
            field=models.IntegerField(null=True),
        ),
    ]
