# Generated by Django 6.0.1 on 2026-01-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_emp_mgr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='MGR',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
