# Generated by Django 6.0.1 on 2026-01-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_emp_mgr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='MGR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp'),
        ),
    ]
